services:
  postgres:
    image: postgres:15
    container_name: poker-db
    environment:
      POSTGRES_DB: poker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: >
        bash -c "
          pg_isready -U user -d poker &&
          psql -U user -d poker -c 'SELECT 1;'"
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: poker-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/poker
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: poker-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: sh -c "pnpm install && pnpm dev"

volumes:
  postgres_data:
